# This workflow will do a clean install of node dependencies, build the source code and run tests

name: Test React App CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        #         node-version: [10.x, 12.x, 14.x]
        node-version: [10.x]

    steps:
      - name: Checkout repo under GITHUB_WORKSPACE
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Clean install node modules
        run: npm ci
      - name: Install jest junit reporter
        run: npm install -D jest-junit-reporter
      - name: Run unit tests
        run: npm run test:ci
      - name: build the project
        run: npm run build --if-present
