# This workflow will do a clean install of node dependencies, build the source code and run tests

name: Test React App CI / CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        #         node-version: [10.x, 12.x, 14.x]
        node-version: [10.x]

    steps:
      - name: Checkout repo under GITHUB_WORKSPACE
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Clean install node modules
        run: npm ci
      - name: Install jest junit reporter
        run: npm install -D jest-junit-reporter
      - name: Run unit tests
        run: npm run test:ci
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Unit Test Results
          files: test-report.xml
          report_individual_runs: true
      - name: Publish code coverage report
        uses: 5monkeys/cobertura-action@master
        with:
          path: "**/cobertura-coverage.xml"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 25
      - name: Run Sonacloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: build the project
        run: npm run build --if-present
